# Generated by Django 3.2.16 on 2022-12-30 00:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ice_cream', '0003_auto_20221229_2158'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('output_order', 'title'), 'verbose_name': 'категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='icecream',
            options={'ordering': ('output_order', 'title'), 'verbose_name': 'мороженое', 'verbose_name_plural': 'Мороженое'},
        ),
    ]