# Generated by Django 3.2.2 on 2021-05-11 14:33
from django.conf import settings
from django.contrib.auth.hashers import make_password
from django.db import migrations


def add_user(apps, schema_editor):
    """Создаем Тохе юзера"""
    User = apps.get_model(*settings.AUTH_USER_MODEL.split('.'))
    User.objects.create(
        username='Toha',
        email='toha@chekh.ru',
        password=make_password('s3cr3tp4ssw0rd!'),
    )


def remove_user(apps, schema_editor):
    """Удаляем юзера"""
    User = apps.get_model(*settings.AUTH_USER_MODEL.split('.'))
    User.objects.get(email='toha@chekh.ru').delete()


def populate_posts(apps, schema_editor):
    """Наполняем базу постами, которые можно будет получить через API."""
    Post = apps.get_model('posts', 'Post')
    User = apps.get_model(*settings.AUTH_USER_MODEL.split('.'))
    author = User.objects.get(email='toha@chekh.ru')
    posts_list = [
        {
            'text': '4 май. Приходили в гости монахи из монастыря. '
            'Приезжала Даша Мусина-Пушкина, вдова инженера Глебова, '
            'убитого на охоте, она же Цикада. Много пела.',
            'author': author,
            'pub_date': '1897-05-04 00:00:00',
        },
        {
            'text': 'Меня пишет художник Браз (для Третьяковской галереи). '
            'Позирую по два раза в день.',
            'author': author,
            'pub_date': '1897-07-13 00:00:00',
        },
        {
            'text': '8-го сент. В Биаррице. Здесь В. М. Соболевский и В. А. Морозова. '
            'Каждый русский в Биаррице жалуется, что здесь много русских.',
            'author': author,
            'pub_date': '1897-09-08 00:00:00',
        },
        {
            'text': '14 сент. Байона. Grande course landaise. Бой с коровами.',
            'author': author,
            'pub_date': '1897-09-14 00:00:00',
        },
        {
            'text': '9 окт. Видел, как мать Башкирцевой играла в рулетку. Неприятное зрелище.',
            'author': author,
            'pub_date': '1897-10-09 00:00:00',
        },
    ]
    Post.objects.bulk_create([Post(**post) for post in posts_list])


def delete_posts(apps, schema_editor):
    """Удаляем посты из базы."""
    Post = apps.get_model('posts', 'Post')
    User = apps.get_model(*settings.AUTH_USER_MODEL.split('.'))
    author = User.objects.get(email='toha@chekh.ru')
    Post.objects.filter(author=author).delete()


class Migration(migrations.Migration):
    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_user, remove_user),
        migrations.RunPython(populate_posts, delete_posts),
    ]
