# Generated by Django 4.2.7 on 2024-01-27 11:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0002_auto_20210605_1416"),
        (
            "posts",
            "0003_alter_comment_id_alter_follow_id_alter_group_id_and_more",
        ),
    ]

    operations = []
