# Generated by Django 4.2.7 on 2024-01-27 14:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0004_merge_20240127_1122"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tagpost",
            name="post",
        ),
        migrations.RemoveField(
            model_name="tagpost",
            name="tag",
        ),
        migrations.RemoveField(
            model_name="post",
            name="tag",
        ),
        migrations.AlterField(
            model_name="post",
            name="group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="group",
                to="posts.group",
            ),
        ),
        migrations.DeleteModel(
            name="Tag",
        ),
        migrations.DeleteModel(
            name="TagPost",
        ),
    ]
